server:
  port: ${SERVER_PORT}

spring:
  application:
    name: AccBalSystem
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  r2dbc:
    url: ${R2DBC_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    url: ${LB_DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
    default-schema: public
currencies:
  api:
    url: https://api.freecurrencyapi.com/v1/latest
    key: ${API_KEY}
